project:
  type: website

website:
  title: "rizdiaprilian.github.io"
  site-url: https://rizdiaprilian.github.io/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rizdiaprilian
      - icon: file-earmark-code
        href: https://www.kaggle.com/kurosakishusuke
format:
  html:
    theme: cosmo
    css: styles.css




